title: Davide Depau
man_title: Davide Depau's Website
url: "https://depau.eu"
baseurl: ""
page_source_base: "https://github.com/Depau/depau.eu/blob/master/"

markdown: kramdown

permalink: pretty

footer: yes
footer_url: "https://github.com/Depau/depau.eu"
footer_text: "Site source code on GitHub"

sass:
    style: compressed
    sass_dir: _sass

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

nav:
 - name: "home"
   link: "/"
   section: "<i class='remixicon-home-line'></i>"
 - name: "blog"
   link: "https://blog.depau.eu"
   section: "<i class='remixicon-newspaper-line'></i>"
 - name: "github"
   link: "https://github.com/Depau"
   section: "<i class='remixicon-github-line'></i>"
 - name: "etchdroid"
   link: "https://etchdroid.depau.eu"
   section: "<i class='remixicon-android-line'></i>"
